### ISSUE TITLE
Support option for Literal

### ISSUE THREAD

**Issue by wenerme** [sinclairzx81/typebox-workbench#6]

**Comment by sinclairzx81** [comment]
@wenerme Hi,

I believe this is already be supported?

[Workbench Link](https://sinclairzx81.github.io/typebox-workbench/?share=LyoqCiAqIEBmb28gMQogKiBAYmFyIDIKICogQGJheiAzCiAqLwpleHBvcnQgdHlwZSBBID0gJ2hlbGxvJwoKZXhwb3J0IHR5cGUgQiA9IHsKICAvKioKICAgKiBAZm9vIDEKICAgKiBAYmFyIDIKICAgKiBAYmF6IDMKICAgKi8KICB2YWx1ZTogJ3dvcmxkJwp9)

Did you mean something else?

**Comment by wenerme** [comment]
For union type value, I tested in my local setup, this could be done

**Comment by sinclairzx81** [comment]
@wenerme Hiya,

Will keep this issue open and revisit in future. This principally to support the following composition.

```typescript
type X = /** @title A */ {
  a: 1
} & /** @title B */ {
  b: 2
}
```

**Comment by wenerme** [comment]
My primary usecase is

```ts
/**
 * @$id InvestorType
 * @title 投资方类型
 */
export type InvestorType = /** @title 本土 */ 'Domestic' | /** @title 外国 */ 'Foreign';

/**
 * @$id NationalityType
 * @title 国籍
 */
export type NationalityType = /** @title 中国 */ 'CN' | /** @title 美国 */ 'US';
```

there is no sulution for this.

for

```ts
type X = /** @title A */ {
  a: 1
} & /** @title B */ {
  b: 2
}
```

I thinks this is the same as `interface X extends A,B{}`, the problem is how to merge the options.

**Comment by sinclairzx81** [comment]
> there is no sulution for this.

But isn't this already possible? (you just need to apply JSDoc comments to named types)

```typescript
// -----------------------------------------------------------
// InvestorType
// -----------------------------------------------------------
/** 
 * @title 本土 
 */ 
type Domestic = 'Domestic'
/**
 *  @title 外国
 */
type Foreign = 'Foreign'
/**
 * @$id InvestorType
 * @title 投资方类型
 */
export type InvestorType = Domestic | Foreign

// -----------------------------------------------------------
// NationalityType
// -----------------------------------------------------------
/**
 * @title 中国
 */
export type CN = 'CN'
/** 
 * @title 美国 
 */
export type US = 'US'

/**
 * @$id NationalityType
 * @title 国籍
 */
export type NationalityType = CN | US
```

**Comment by wenerme** [comment]
> But isn't this already possible?

Sorry, forgot this, but there are too many enum/const, every value is a type makes maintain too hard. I'm ok if you thinks the proposal should be reconsidered.

**Comment by sinclairzx81** [comment]
@wenerme Hi,

Hey, might close off this issue as I don't think ill be able to implement this under the current codegen infrastructure. The difficulty here is that the inline union variants don't have named types associated with them, and because of this, it's not trivial to apply the interior doc comment.

The implementation of JSDoc comments isn't well integrated with the TS compiler API currently, I may reinvestigate this in future, but probably once the TS > TB codegen is revised (which is a long way off). 

For now, will close off with the recommendation to pull union variants into their own named types.
All the best!
S
